server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://172.31.20.20:3100/loki/api/v1/push

scrape_configs:
  - job_name: system_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: system_logs
          host: localhost
          __path__: /var/log/*log

  - job_name: nginx_logs
    static_configs:
      - targets:
          - localhost
        labels:
          __path__: /var/log/nginx/*.log
          job: nginx
          host: localhost


  - job_name: docker_logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
#        regex: ^/zillout$
        target_label: container_name
      - source_labels: [__meta_docker_container_id]
        target_label: container_id

  - job_name: docker
    pipeline_stages:
      - docker: {}
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker-logs
          __path__: /var/lib/docker/containers/*/*.log
