server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Scraping system logs (existing)
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  # Scraping logs from the Java application
- job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          container_name: zillout  # Label for identifying logs of this container
          __path__: /var/lib/docker/containers/zillout/*-json.log

  # Scraping logs from Nginx
  - job_name: nginx-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          __path__: /var/log/nginx/*.log

