server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://172.31.28.178:3100/loki/api/v1/push

scrape_configs:
  - job_name: system_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: system_logs
          host: localhost
          __path__: /var/log/*log

  - job_name: nginx_logs
    static_configs:
      - targets:
          - localhost
        labels:
          __path__: /var/log/nginx/*.log
          job: nginx
          host: localhost

  - job_name: dockers_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*json
