version: "3.9"

services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
      - "9096:9096"  # Expose the gRPC port if needed
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
      - ./loki:/etc/loki  # Mount the Loki configuration
      - ./loki-data:/loki  # Ensure this directory exists for storage
    command: -config.file=/etc/loki/loki-config.yaml
    restart: unless-stopped
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    ports:
      - "9080:9080"
    volumes:
      - ./loki/promtail-config.yaml:/etc/promtail/promtail-config.yaml
#      - /var/lib/docker/containers:/var/lib/docker/containers:ro
 #     - /var/log/nginx:/var/log/nginx:ro
  #    - ./positions:/tmp
    command: -config.file=/etc/promtail/promtail-config.yaml -config.expand-env=true
    restart: unless-stopped
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - /home/ubuntu/grafana.ini:/etc/grafana/grafana.ini
    networks:
      - monitoring

networks:
  monitoring:
    name: monitoring
    driver: bridge

volumes:
  grafana-data:
    driver: local
  loki-data:
    driver: local
