scrape_configs:
  - job_name: 'MyAppMetrics'
    metrics_path: '/api/v1/rbzo/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['192.168.100.1:7009']
        labels:
          application: 'My Spring Boot Application'