scrape_configs:
  - job_name: 'MyAppMetrics'
    metrics_path: '/api/v1/rbzo/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['172.31.25.63:7009']
        labels:
          application: 'My Spring Boot Application'
